### POST todo 생성
POST localhost:8080/api/todos
Content-type: application/json

{
    "title": "제목",
    "description": "설명",
    "done": false
}


### GET 모든 todo 조회
GET localhost:8080/api/todos

### 특정 todo 조회
GET localhost:8080/api/todos/1


//////////////////////////////////

### Board 생성
POST localhost:8080/posts
Content-Type: application/json

{
    "title": "제목",
    "content": "내용",
    "createdBy": "작성자"
}

### Board 수정
PUT localhost:8080/posts/1
Content-Type: application/json

{
    "title": "제목",
    "content": "내용",
    "updatedBy": "수정자"
}

### Board 삭제
DELETE localhost:8080/posts/1?createdBy=john


### Board 상세 조회
GET localhost:8080/posts/1


### Board 목룍 조회
GET localhost:8080/posts?page=0&size=10&title=title&createdBy=john

